/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinare.view;

import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import vaccinare.model.Crianca;
import vaccinare.model.Usuario;
import vaccinare.model.Vacina;
import vaccinare.model.Vacinacao;

/**
 *
 * @author lucas.270498
 */
public class JFrameVacinacoes extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCriancas
     */
    public JFrameVacinacoes() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        String idUser = Integer.toString(Usuario.authId);
        jTextFieldIDAplicador.setText(idUser);
        jTextFieldAplicador.setText(Usuario.authName);
        java.util.Date d = new Date();
        String dStr = java.text.DateFormat.getDateInstance(DateFormat.MEDIUM).format(d);
        jTextFieldData.setText(dStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVacinas = new javax.swing.JTable();
        jButtonLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCriancas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVacinacoes = new javax.swing.JTable();
        jTextFieldNomeCria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonPesquisar1 = new javax.swing.JButton();
        jTextFieldIDCria = new javax.swing.JTextField();
        jTextFieldIDVacina = new javax.swing.JTextField();
        jTextFieldIDAplicador = new javax.swing.JTextField();
        jTextFieldAplicador = new javax.swing.JTextField();
        jTextFieldNomeVacina = new javax.swing.JTextField();
        jTextFieldData = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCrianca1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestão de Vacinações"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("ID");

        jTextFieldID.setEnabled(false);

        jLabel3.setText("Vacina");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/search-user.png"))); // NOI18N
        jButtonPesquisar.setText("Listar Dados");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Aplicação: ");

        jLabel5.setText("Aplicador:");

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/add-user.png"))); // NOI18N
        jButtonCadastrar.setText("Adicionar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/update-user.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/delete-user.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableVacinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVacinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVacinasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVacinas);
        if (jTableVacinas.getColumnModel().getColumnCount() > 0) {
            jTableVacinas.getColumnModel().getColumn(0).setResizable(false);
            jTableVacinas.getColumnModel().getColumn(1).setResizable(false);
            jTableVacinas.getColumnModel().getColumn(1).setHeaderValue("Nome da Vacina");
        }

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/clear.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jTableCriancas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome da Criança"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCriancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCriancasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCriancas);
        if (jTableCriancas.getColumnModel().getColumnCount() > 0) {
            jTableCriancas.getColumnModel().getColumn(0).setResizable(false);
        }

        jTableVacinacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Vacinacao", "Criança", "Aplicador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVacinacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVacinacoesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableVacinacoes);
        if (jTableVacinacoes.getColumnModel().getColumnCount() > 0) {
            jTableVacinacoes.getColumnModel().getColumn(0).setResizable(false);
            jTableVacinacoes.getColumnModel().getColumn(1).setResizable(false);
            jTableVacinacoes.getColumnModel().getColumn(2).setResizable(false);
        }

        jTextFieldNomeCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCriaActionPerformed(evt);
            }
        });

        jButtonPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/search-user.png"))); // NOI18N
        jButtonPesquisar1.setText("Pesquisar");
        jButtonPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisar1ActionPerformed(evt);
            }
        });

        jTextFieldIDCria.setEnabled(false);
        jTextFieldIDCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDCriaActionPerformed(evt);
            }
        });

        jTextFieldIDVacina.setEnabled(false);

        jTextFieldIDAplicador.setEnabled(false);

        jTextFieldAplicador.setEnabled(false);

        jTextFieldNomeVacina.setEnabled(false);

        jTextFieldData.setEnabled(false);

        jLabel6.setText("Criança:");

        jTextFieldCrianca1.setEnabled(false);

        jLabel7.setText("ID Criança");

        jLabel8.setText("ID Vacina");

        jLabel9.setText("ID Aplicador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCrianca1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldIDCria))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel8))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addComponent(jTextFieldIDVacina)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldIDAplicador)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonCadastrar)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButtonAlterar)
                                    .addGap(38, 38, 38)
                                    .addComponent(jButtonExcluir)
                                    .addGap(43, 43, 43)
                                    .addComponent(jButtonLimpar))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNomeCria)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonPesquisar1)))
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPesquisar)
                                .addGap(113, 113, 113))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIDCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIDVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIDAplicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAplicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCrianca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCadastrar)
                            .addComponent(jButtonAlterar)
                            .addComponent(jButtonExcluir)
                            .addComponent(jButtonLimpar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButtonPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomeCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar1))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar1ActionPerformed
        try {
            ArrayList<Vacinacao> vacinacoes = null;

            DefaultTableModel tableModel = (DefaultTableModel) jTableVacinacoes.getModel();
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            //Crio o Model de Vacinas
            Vacinacao vacinacao = new Vacinacao();

            //Realizo a pesquisa
            String nome = jTextFieldNomeCria.getText();
            //E salvo em um array
            vacinacoes = vacinacao.select(nome);

            if (!vacinacoes.isEmpty()) {
                //percorre o array e adiciono ao DefaultTableModel
                for (Vacinacao vc : vacinacoes) {
                    tableModel.addRow(new Object[]{vc.getId(), vc.getCrianca().getNome(), vc.getAplicador().getLogin()});
                }
                //Associo a o tableModel ao componente na tela
                jTableVacinacoes.setModel(tableModel);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Lamento, mas esta pesquisa não retornou registros.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPesquisar1ActionPerformed

    private void jTableVacinacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVacinacoesMouseClicked
        try {
            //Pego a linha selecionada na tela
            int row = jTableVacinacoes.getSelectedRow();

            //Pego o DefaultTableModel do componente de JTable do Java
            DefaultTableModel tableModel = (DefaultTableModel) jTableVacinacoes.getModel();
            //pego o ID da Crianca pela tela
            int id = (int) tableModel.getValueAt(row, 0);
            //Crio a viagem vazia
            Vacinacao vacinacao = new Vacinacao();
            //Pesquiso e retorno um chamado com os dados do banco
            vacinacao.selectAttributes(id);
            
            jTextFieldIDCria.setText(Integer.toString(vacinacao.getCrianca().getId()));
//            jTextFieldIDAplicador.setText(Integer.toString(id));
//            jTextFieldID.setText(Integer.toString(id));
//            jTextFieldIDVacina.setText(Integer.toString(id));
//            jTextFieldCrianca1.setText(nome);
//            jTextFieldIDVacina.setText(Integer.toString(id));
//            jTextFieldNomeVacina.setText(nome);
            

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableVacinacoesMouseClicked

    private void jTableCriancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCriancasMouseClicked
        try {
            //Pego a linha selecionada na tela
            int row = jTableCriancas.getSelectedRow();

            //Pego o DefaultTableModel do componente de JTable do Java
            DefaultTableModel tableModel = (DefaultTableModel) jTableCriancas.getModel();
            //pego o ID e Nome da Crianca pela tela
            int id = (int) tableModel.getValueAt(row, 0);
            String nome = (String) tableModel.getValueAt(row, 1);

            jTextFieldIDCria.setText(Integer.toString(id));
            jTextFieldCrianca1.setText(nome);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableCriancasMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed

        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTableVacinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVacinasMouseClicked
        try {
            //Pego a linha selecionada na tela
            int row = jTableVacinas.getSelectedRow();

            //Pego o DefaultTableModel do componente de JTable do Java
            DefaultTableModel tableModel = (DefaultTableModel) jTableVacinas.getModel();
            //pego o ID e Nome da Vacina pela tela
            int id = (int) tableModel.getValueAt(row, 0);
            String nome = (String) tableModel.getValueAt(row, 1);

            jTextFieldIDVacina.setText(Integer.toString(id));
            jTextFieldNomeVacina.setText(nome);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableVacinasMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {

            // Passa os dados da view para a Model
            Vacinacao vacinacao = new Vacinacao();
            vacinacao.setId(Integer.parseInt(jTextFieldID.getText()));
            //Chamo o método de exclusão
            vacinacao.delete();

            JOptionPane.showMessageDialog(rootPane, "Vacinação excluída com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {

            // Passa os dados da view para a Model
            Vacinacao vacinacao = new Vacinacao();
            Vacina vacina = new Vacina();
            vacina.setId(Integer.parseInt(jTextFieldIDVacina.getText()));
            Crianca cria = new Crianca();
            cria.setId(Integer.parseInt(jTextFieldIDCria.getText()));
            Usuario user = new Usuario();
            user.setId(Usuario.authId);

            vacinacao.setAplicador(user);
            vacinacao.setCrianca(cria);
            vacinacao.setVacina(vacina);

            String date = jTextFieldData.getText();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(date).getTime());

            vacinacao.setDataAplicacao(data);

            vacinacao.insert();

            JOptionPane.showMessageDialog(rootPane, "Vacinacão cadastrada com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        try {

            //Crio o array vazio de Criancas
            ArrayList<Crianca> criancas = null;

            //Pego o DefaultTableModel do componente de JTable do Java
            DefaultTableModel tableModel = (DefaultTableModel) jTableCriancas.getModel();
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            //Crio o Model de Crianca
            Crianca crianca = new Crianca();

            //Realizo a pesquisa
            String pesquisa = "";
            //E salvo em um array
            criancas = crianca.select(pesquisa);

            if (!criancas.isEmpty()) {
                //percorre o array e adiciono ao DefaultTableModel
                for (Crianca cr : criancas) {
                    tableModel.addRow(new Object[]{cr.getId(), cr.getNome(), cr.getIdade()});
                }
                //Associo a o tableModel ao componente na tela
                jTableCriancas.setModel(tableModel);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Lamento, mas esta pesquisa não retornou registros.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }

        try {
            ArrayList<Vacina> vacinas = null;

            DefaultTableModel tableModel = (DefaultTableModel) jTableVacinas.getModel();
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            //Crio o Model de Vacinas
            Vacina vacina = new Vacina();

            //Realizo a pesquisa
            String pesquisa = "";
            //E salvo em um array
            vacinas = vacina.select(pesquisa);

            if (!vacinas.isEmpty()) {
                //percorre o array e adiciono ao DefaultTableModel
                for (Vacina v : vacinas) {
                    tableModel.addRow(new Object[]{v.getId(), v.getNomeVacina(), v.getNumeroLote()});
                }
                //Associo a o tableModel ao componente na tela
                jTableVacinas.setModel(tableModel);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Lamento, mas esta pesquisa não retornou registros.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:" + ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldNomeCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCriaActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "As alterações desse cadastro foram desativadas.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldIDCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDCriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDCriaActionPerformed

    public boolean limparCampos() {

        Component componentes[] = jPanel1.getComponents();
        for (Component c : componentes) {
            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            } else if (c instanceof JComboBox) {
                ((JComboBox) c).setSelectedIndex(0);
            } else if (c instanceof JRadioButton) {
                ((JRadioButton) c).setSelected(true);

            }
        }
        return true;

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCriancas;
    private javax.swing.JTable jTableVacinacoes;
    private javax.swing.JTable jTableVacinas;
    private javax.swing.JTextField jTextFieldAplicador;
    private javax.swing.JTextField jTextFieldCrianca1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDAplicador;
    private javax.swing.JTextField jTextFieldIDCria;
    private javax.swing.JTextField jTextFieldIDVacina;
    private javax.swing.JTextField jTextFieldNomeCria;
    private javax.swing.JTextField jTextFieldNomeVacina;
    // End of variables declaration//GEN-END:variables
}
