/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinare.view;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import vaccinare.model.Crianca;

/**
 *
 * @author mauricio.rosito
 */
public class JFrameCriancas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCriancas
     */
    public JFrameCriancas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jCheckBoxParto = new javax.swing.JCheckBox();
        jTextFieldMae = new javax.swing.JTextField();
        jRadioButtonBranca = new javax.swing.JRadioButton();
        jRadioButtonNegra = new javax.swing.JRadioButton();
        jRadioButtonParda = new javax.swing.JRadioButton();
        jRadioButtonIndigena = new javax.swing.JRadioButton();
        jRadioButtonAmarela = new javax.swing.JRadioButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCriancas = new javax.swing.JTable();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestão de Crianças"));

        jLabel1.setText("ID:");

        jTextFieldID.setEnabled(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Idade:");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/search-user.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel4.setText("Sexo:");

        jLabel5.setText("Parto:");

        jLabel6.setText("Mãe:");

        jLabel7.setText("Cor/Etnia:");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));

        jCheckBoxParto.setText("Natural");

        buttonGroupSexo.add(jRadioButtonBranca);
        jRadioButtonBranca.setSelected(true);
        jRadioButtonBranca.setText("Branca");

        buttonGroupSexo.add(jRadioButtonNegra);
        jRadioButtonNegra.setText("Negra");

        buttonGroupSexo.add(jRadioButtonParda);
        jRadioButtonParda.setText("Parda");

        buttonGroupSexo.add(jRadioButtonIndigena);
        jRadioButtonIndigena.setText("Indígena");

        buttonGroupSexo.add(jRadioButtonAmarela);
        jRadioButtonAmarela.setText("Amarela");

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/add-user.png"))); // NOI18N
        jButtonCadastrar.setText("Adicionar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/update-user.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/delete-user.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableCriancas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Idade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCriancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCriancasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCriancas);
        if (jTableCriancas.getColumnModel().getColumnCount() > 0) {
            jTableCriancas.getColumnModel().getColumn(0).setResizable(false);
        }

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinare/view/img/clear.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonExcluir)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonLimpar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonBranca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonNegra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonParda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonIndigena)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonAmarela))
                                    .addComponent(jCheckBoxParto)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMae, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonCadastrar)
                            .addGap(61, 61, 61)
                            .addComponent(jButtonAlterar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(105, 105, 105))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBoxParto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonBranca)
                        .addComponent(jRadioButtonNegra)
                        .addComponent(jRadioButtonParda)
                        .addComponent(jRadioButtonIndigena)
                        .addComponent(jRadioButtonAmarela)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        /*Transformei numa função porque chamo ela dentro do excluir pra tirar 
        o contato excluído*/
        listaCriancas();
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    public void listaCriancas(){
        try {
            
            //Crio o array vazio de Criancas
            ArrayList<Crianca> criancas = null;
            
            //Pego o DefaultTableModel do componente de JTable do Java
            DefaultTableModel  tableModel = (DefaultTableModel) jTableCriancas.getModel();
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            //Crio o Model de Crianca
            Crianca crianca = new Crianca();
            
            //Realizo a pesquisa
            String nome = jTextFieldNome.getText();
            //E salvo em um array
            criancas = crianca.listar(nome);
            
            if(criancas!=null){
                //percorre o array e adiciono ao DefaultTableModel
                for (Crianca cr : criancas) {
                    tableModel.addRow(new Object[]{cr.getId(), cr.getNome(), cr.getIdade()});
                }
                //Associo a o tableModel ao componente na tela
                jTableCriancas.setModel(tableModel);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Lamento, mas esta pesquisa não retornou registros.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:"+ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean limparCampos() {  
  
            Component componentes[] = jPanel1.getComponents();  
            for (Component c : componentes) {  
                if (c instanceof JTextField) {  
                    ((JTextField) c).setText("");  
                } else if (c instanceof JComboBox) {  
                    ((JComboBox) c).setSelectedIndex(0);  
                }else if (c instanceof JRadioButton) {  
                    ((JRadioButton) c).setSelected(true);  
                      
                }  
            }  
            return true;  
  
    }  
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
        limparCampos();
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {
            
            
            // Passa os dados da view para a Model
            Crianca crianca = new Crianca();
            
            crianca.setNome(jTextFieldNome.getText());
            crianca.setIdade(Integer.parseInt(jTextFieldIdade.getText()));
            crianca.setSexo(jComboBoxSexo.getSelectedItem().toString());
            crianca.setPartoNatural(jCheckBoxParto.isSelected());
            crianca.setMae(jTextFieldMae.getText());
            if(jRadioButtonBranca.isSelected()) crianca.setEtnia("branca");
            if(jRadioButtonAmarela.isSelected()) crianca.setEtnia("amarela");
            if(jRadioButtonIndigena.isSelected()) crianca.setEtnia("indigena");
            if(jRadioButtonNegra.isSelected()) crianca.setEtnia("negra");
            if(jRadioButtonParda.isSelected()) crianca.setEtnia("parda");
                
            // Chama o método inserir
            crianca.inserir();
            
            JOptionPane.showMessageDialog(rootPane, "Criança cadastrada com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:"+ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
         try {
            
            // Passa os dados da view para a Model
            Crianca crianca = new Crianca();
            crianca.setId(Integer.parseInt(jTextFieldID.getText()));
            crianca.setNome(jTextFieldNome.getText());
            crianca.setIdade(Integer.parseInt(jTextFieldIdade.getText()));
            crianca.setSexo(jComboBoxSexo.getSelectedItem().toString());
            crianca.setPartoNatural(jCheckBoxParto.isSelected());
            crianca.setMae(jTextFieldMae.getText());
            if(jRadioButtonBranca.isSelected()) crianca.setEtnia("branca");
            if(jRadioButtonAmarela.isSelected()) crianca.setEtnia("amarela");
            if(jRadioButtonIndigena.isSelected()) crianca.setEtnia("indigena");
            if(jRadioButtonNegra.isSelected()) crianca.setEtnia("negra");
            if(jRadioButtonParda.isSelected()) crianca.setEtnia("parda");
            
            //Chamo o método para atualizar
            crianca.atualizar();
            
            JOptionPane.showMessageDialog(rootPane, "Criança modificada com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:"+ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            
            // Passa os dados da view para a Model
            Crianca crianca = new Crianca();
            crianca.setId(Integer.parseInt(jTextFieldID.getText()));
            //Chamo o método de exclusão
            crianca.excluir();
                        
            JOptionPane.showMessageDialog(rootPane, "Criança excluída com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:"+ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
        listaCriancas();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableCriancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCriancasMouseClicked
         try {
            //Pego a linha selecionada na tela
            int row = jTableCriancas.getSelectedRow();
            
            //Pego o DefaultTableModel do componente de JTable do Java
            DefaultTableModel  tableModel = (DefaultTableModel) jTableCriancas.getModel();
            //pego o ID da Crianca pela tela
            int id = (int) tableModel.getValueAt(row, 0);
            //Crio a viagem vazia
            Crianca crianca = new Crianca();
            //Pesquiso e retorno um chamado com os dados do banco
            crianca.buscar(id);
            
            //Coloco os dados que vieram no banco no formulário da tela
            jTextFieldID.setText(String.valueOf(crianca.getId()));
            jTextFieldNome.setText(crianca.getNome());
            jTextFieldIdade.setText(String.valueOf(crianca.getIdade()));
            jComboBoxSexo.setSelectedItem(crianca.getSexo());
            jCheckBoxParto.setSelected(crianca.isPartoNatural());
            jTextFieldMae.setText(crianca.getMae());
            switch (crianca.getEtnia()){
                case "amarela":
                    jRadioButtonAmarela.setSelected(true);
                    break;
                case "branca":
                    jRadioButtonBranca.setSelected(true);
                    break;
                case "indigena":
                    jRadioButtonIndigena.setSelected(true);
                    break;
                case "negra":
                    jRadioButtonNegra.setSelected(true);
                    break;
                case "parda":
                    jRadioButtonParda.setSelected(true);
                    break;
            }
                      
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lamento, mas tivemos uma ocorrência inesperada no sistema.\n Erro:"+ex.toString(), "Ocorrência Inesperada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableCriancasMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JCheckBox jCheckBoxParto;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAmarela;
    private javax.swing.JRadioButton jRadioButtonBranca;
    private javax.swing.JRadioButton jRadioButtonIndigena;
    private javax.swing.JRadioButton jRadioButtonNegra;
    private javax.swing.JRadioButton jRadioButtonParda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCriancas;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldMae;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
